### PR TITLE
Update import/setupDB.js

### PR DESCRIPTION
**Pull request by tk120404**
corrected location index

### CODE REVIEW

**Comment by csaoh** [comment]
Hello, 

I kind of fail to see what is wrong with the current version and why does this index name need to be changed, since it seems to work fine. Would you mind explain it to me ?

Thanks !

**Comment by tk120404** [comment]
I think  in 'loc : "2d" ', loc has to be name of the location field. so I
changed it pin.location.

On Wed, Jan 30, 2013 at 3:34 PM, Andrey Kalinovsky <notifications@github.com

> wrote:
> 
> Hello,
> 
> I kind of fail to see what is wrong with the current version and why does
> this index name need to be changed, since it seems to work fine. Would you
> mind explain it to me ?
> 
> Thanks !
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alchemy-fr/GeonamesServer/pull/20#issuecomment-12882489.

## 

with regards
Arjun kumar T.K.

**Comment by romainneutron** [comment]
This is right, indeed !

**Comment by romainneutron** [comment]
thanks !

**Pull request merged**
